//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

public class Land : Voxel
{
	static GameObject originalObject;

	/// <summary>
	/// Initializes a new instance of the Land class.
	/// </summary>
	public Land()
	{
		originalObject = init ();
	}

	/// <summary>
	/// Gets the original GameObject.
	/// </summary>
	/// <returns>The original.</returns>
	public override GameObject getOriginal ()
	{
		return base.getOriginal ();
	}

	/// <summary>
	/// Gets the prefab path.
	/// </summary>
	/// <returns>The prefab path.</returns>
	public override string getPrefabPath ()
	{
		return "hello";
	}

	/// <summary>s
	/// Update this instance.
	/// </summary>
	public override void Update ()
	{

	}

	/// <summary>
	/// Start this instance.
	/// </summary>
	public override void Start ()
	{

	}
}

