//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Land : Voxel
{
	static GameObject originalObject;

	public Land()
	{
		originalObject = init ();
	}

	public override UnityEngine.GameObject getOriginal ()
	{
		return originalObject;
	}

	public override string getPrefabPath ()
	{
		return "";
	}

	public override void Update ()
	{
		base.Update ();
	}

	public override void Start ()
	{
		base.Start ();
	}
}

