//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

public class Land : Voxel
{
	public static GameObject originalObject;
	public GameObject normalObject;

	/// <summary>
	/// Initializes a new instance of the Land class.
	/// </summary>
	public Land(Vector3 position)
	{
		initialize ();

		normalObject = (GameObject)Instantiate(originalObject, position, Quaternion.Euler(270,90,0));
		normalObject.AddComponent ("Land");
	}

	protected static void initialize()
	{
		if(originalObject == null)
			originalObject = init ("Land1");
	}

	/// <summary>
	/// Gets the original GameObject.
	/// </summary>
	/// <returns>The original.</returns>
	public static GameObject getOriginal ()
	{
		initialize ();

		return originalObject;
	}

	/// <summary>s
	/// Update this instance.
	/// </summary>
	public override void Update ()
	{

	}

	/// <summary>
	/// Start this instance.
	/// </summary>
	public override void Start ()
	{

	}
}

